### PR TITLE
Added Trump inauguration

### PR DESCRIPTION
**Pull request by uargh**

### CODE REVIEW

**Comment by alexbowers** [comment]
I'm going to hold off on this.

Whilst I personally agree, it isn't objectively a "sucky" thing. 

I'm going to wait for him to do stupid stuff, which _can_ be added.

Also, the date format is incorrect, we use dashes not periods

**Comment by alexbowers** [comment]
For future reference, here is the patch if I decide to change my mind:

```
From 87dbcdd159623efaa687bacc15e7965e1f1f9566 Mon Sep 17 00:00:00 2001
From: Jonas <uargh@users.noreply.github.com>
Date: Wed, 25 Jan 2017 08:41:15 +0100
Subject: [PATCH] Added Trump inauguration

---
 data/events.json | 15 +++++++++++++++
 1 file changed, 15 insertions(+)

diff --git a/data/events.json b/data/events.json
index 20885ca..67ebb63 100644
--- a/data/events.json
+++ b/data/events.json
@@ -118,5 +118,20 @@
                 ]
             }
         ]
+    },
+    {
+        "date": "20.01.2017",
+        "items": [
+            {
+                "title": "Donald J. Trump inaugurated as 45th. US president",
+                "description": [
+                    "A large number of protests against Donald Trump, both in the U.S. and abroad, occurred in connection with the inauguration of Donald Trump as the 45th President of the United States of America.",
+                    "Due to the preparation, scale and turnout of the protests they have been called one of the largest of the current century."
+                ],
+                "sources": [
+                    "http://https://www.nytimes.com/2017/01/20/us/politics/donald-trump-inauguration.html"
+                ]
+            }
+        ]
     }
 ]
```

What would cause me to change my mind would be a significant number of bad events directly the result of his presidency.

**Comment by uargh** [comment]
First bad event: Global gag rule reinstated

**Comment by alexbowers** [comment]
I am more than happy for that event to be added to the list.

**Comment by uargh** [comment]
Yeah...pull request coming soon ;)

**Pull request closed without merging**
