### PR TITLE
Donald J. Trump reinstates global gag rule

### PR DESCRIPTION
**Pull request by uargh**

### CODE REVIEW

**Comment by alexbowers** [comment]
Please can the title contain "President Trump" instead of "Donald J Trump"

**Comment by uargh** [comment]
Sure thing

**Comment by alexbowers** [comment]
`nongovernmental` should have a hyphen too I think.

Thats the only other issue, and then its ready for merging :)

**Comment by uargh** [comment]
Fixed the typo

**Comment by alexbowers** [comment]
Thanks

**Comment by alexbowers** [comment]
https://2017.sucks/#/president-trump-reinstates-global-gag-rule

**Pull request merged**
